# Site configuration
domain: "https://yuliuu.com"
baseurl: " " # the subpath of your site, e.g. /blog
url: "https://jaydenyl.github.io/" # the base hostname & protocol for your site
permalink: /:title/
avatar: /assets/IMG_1832.JPG   #  头像
about: /assets/about.jpg
favicon: /assets/IMG_1832.JPG #原来是favicon.ico 不知道是否一定要ico文件 ... ... 好吧，并不
basecss: 
# Theme specific configuration
title: YULIU's BLOG
description: >
  Reading is fundamental and fun to mental.

# Contact and social media links
#twitter_username: songrogero
#github_username: songroger
#facebook_username: song.roger.1
#instagram_username: songroger198
#linkedin_username: songroger

exclude: ['node_modules', 'gulpfile.js', 'package.json']

kramdown:
  input: GFM

# If U enable the comment, edit disqus or duoshuo account
# before deploy your webpage
enable_comment: false
# disqus_account: songroger

# gems: ['jekyll-paginate']
# Pagination
paginate: 100
paginate_path: /archive/page:num

plugins:
    - jekyll-paginate
